import type { Metadata } from 'next';
import { Poppins, Roboto, Inter, Manrope } from 'next/font/google';
import Header from '@/components/shared/Header';
import Footer from '@/components/shared/Footer';
import './globals.scss';

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
    weight: ['800'],
});

const manrope = Manrope({
    variable: '--font-manrope',
    subsets: ['latin'],
    weight: ['400'],
});

const roboto = Roboto({
    variable: '--font-manrope',
    subsets: ['latin'],
    weight: ['400'],
});

const poppins = Poppins({
    variable: '--font-poppins',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${poppins.className} ${roboto.className} ${manrope.className} ${inter.className} antialiased`}
            >
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
